[package]
name = "pint-utils"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
e2e-test.workspace = true
tokio.workspace = true
primitives.workspace = true
hex.workspace = true